---
- name: Setup Docker on Remote-server
  hosts: DockerServer
  gather_facts: false
  become: yes
  tasks:
    - name: Upate package manager and install python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - python3
        update_cache: yes
        state: present
    - name: install Docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - docker
        state: present
    - name: downnload and install Docekr compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}"
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: install docker-python
      ansible.builtin.pip:
        name: 
        - docker
        - docker-compose

- name: start Docker service
  hosts: DockerServer
  become: yes
  gather_facts: false
  tasks:
    - name: Make sure Docker service unit is running
      ansible.builtin.systemd:
        state: started
        name: docker

- name: Add user to Docker Group
  hosts: DockerServer
  become: yes
  gather_facts: false
  tasks:
    - name: Add User to Group
      ansible.builtin.user:
        user: ec2-user
        group: docker
    - name: Reset connection
      ansible.builtin.meta: reset_connection

- name: Setup and run Compose-file
  hosts: DockerServer
  become: yes
  become_user: ec2-user
  gather_facts: false
  vars_files:
    - vars_dockercompose
  tasks:
    - name: Copy docker compose-file
      ansible.builtin.copy:
        src: "{{ file_path_local }}"
        dest: "{{ file_path_remote }}"
    - name: docker login
      community.docker.docker_login: 
        registry_url: "{{ registry_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        reauthorize: yes
    - name: start containers
      community.docker.docker_compose:
        project_src: "{{ file_path_remote }}"
        state: present #default state